tool-template-main:
  container_name: tool-template-main
  build: .
  volumes:
    - "./src:/build/src"

tool-template-tests:
  container_name: tool-template-main
  build: .
  volumes:
    - "./src:/build/src"
    - "./test:/build/test"
  command: python /build/test/test.py

tool-template-examples:
  container_name: tool-template-main
  build: .
  volumes:
    - "./src:/build/src"
    - "./examples:/build/examples"
  command: python /build/test/examples.py
